export const qS = 
`A couple of people were arguing in the supermarket at the fruit and veg counter, but it's busy in there 'cause it's Christmas so that's probably what brought it on. (B) = Bananarama
42 pounds for a torch? That's a bit pricey innit? (D) = Deee-Lite
Well, if he would've been wearing a helmet he'd have been alright. (B) = Busted
This young man prepared for his death. (WY) = Will Young
Better than the average homeless person. (S) = Supertramp
The little girl is hungry; what shall we do? (F) = Feeder
Exploding pet. (AK) = Atomic Kitten
I'll take that book to the toilet with me. (LR) = Lou Reed
Blow the candles out before you eat the cake. (FL) = Flaming Lips
How can I wash up in something shaped like that? (NS) = N-Sync
At the moment I'm in a river full of logs. (JT) = Justin Timberlake
That lad's got bad asthma. (W) = Weezer
I saw Mousetrap the other night, but the heating was knackered and it ruined the evening. (C) = Coldplay
I don't like them birds, they shouldn't be allowed in this area. (B) = The Bangles
That bloke who does sport on telly, he's got a little kid. (DC) = Destiny's Child 
That army has got some well nice trenches. (DW) = Dandy Warhols 
The top of them curtains are wrecked; all the material's worn. (HV) = Holly Valance
I was in Texas the other week, I fell over and landed on my knees in a puddle. (WH) = Whitney Houston
The fella has only got one badge left. (E) = Elastica
The unmarried lady is a friend I eat out with. (MD) = Ms Dynamite
I really really love that woman. I love everything she does. (M) = Madonna
Stop throwing that fruit about. (CB) = Chuck Berry
That Scottish fella has made an error. (M) = Mis-Teeq (mistake)
God, you can make a right load of toast with them. (G) = Gorillaz
You've been dunking that for too long. (LB) = Limp Bizkit
You won't be able to play that game in this pub. The table ain't big enough (FD) = Fats Domino
Well, I've had a rubbish day so I'm happy it's over. (GK) = Gladys Knight
That'll never get off the ground. (LZ) = Led Zeppelin
That woman's got her husbands gloves and a pair of her own. (HH) = Herman's Hermits
You'll get a load of bacon off them. (L) = Longpigs
There's a load of letters there asking for advice. Put them on Claire's desk. Oh and, er, have a good Christmas. (F) = Foreigner
Ask your mum if you should, after you've wrapped the presents. (S) = Shalamar (shall I, ma?)
He'll fit some chocolate to your feet. (A) = Aerosmith
Do you think your kid will get that strawberry for me? (WP) = Wilson Picket
Don't argue with him. He ain't gonna change his mind. (AA) = Adam Ant
He always gets what he wants and doesn't worry about anyone else. (P) = Pixies 
I'll have to put that woman in the oven. (AB) = Anita Baker 
I've got three other jumpers like this one. (FT) = Four Tops
Those people can't make up their minds whether to sit in the sun or not. (C) = Charlatans 
That Jamaican fella needs an aspirin. Why is that? (FP) = Freda Payne
The weather stinks, dunnit? (R) = Rainbow
Look, gran, just get on the boat and help us out will you. (R) = Ronan
If you're going to do that with your drink, I'd wait for it to settle a bit. (CK) = Chaka Khan 
The Australian picks two blokes. (E) = Eminem 
That builder is a bit cute. (BT) = Bonnie Tyler
Why are them Jamaican men swinging fish around their head? (DS) = Detroit Spinners (de trout spinners)
The northern lad remembers he has to tell his mom's daughter something. (O) = Oasis (oh, hey sis)
The person from Birmingham got a C in their degree. (T) = Toto (2.2)
The cockney fella isn't happy. Everything's going wrong. (DH) = Dan Hill (Down hill)
The gingerbread man has only got one leg. (LB) = Limp Bizkit (Limp biscuit)
These people from the East Midlands swear a lot. (TTD) = Terence Trent D'arby (Tourette's Trent Derby)
Have a holiday in Italy. (TB) = Turin Brakes (Turin breaks)
The hitchhiker needs a lift but in something bigger than a car. (VH) = Van Halen (Van hailing)
Don't be selfish, hand some of it out to your mates. (C) = Cher (Share)
The Scottish fellas can't get into their emails. (KL) = Kenny Loggins (cannae login)
Me younger brother spotted you the other day. (JS) = Junior Senior (junior seen yer)
That champagne belongs to the boxer's kid. (AM) = Alison Moyet (Ali's son's Moët)
The vibrators. (B) = Buzzcocks
Oh, they're havin' a few problems and that. They haven't got any rice left. (CC) = China Crisis
The Geordie fella doesn't know what he's being charged for. (BW) = Bill Wyman (bill? why, man?)
I had two bricks and I had to throw 'em at two women, right, and I didn't hit either of 'em. (MM) = Mister Mister (Missed her, missed her)
The customer wanted some paint to darken up her room. The shop assistant knew what to do. (CB) = Cilla Black (sell her black)
It'd be all right if their heads weren't so big. (SF) = Small Faces
Chanel have got another perfume out. (NO) = New Order (new odor)
That fella likes sucking on iron. (M) = Metallica (metal licker)
The Jamaican fella spots a boat. (D) = DeBarge (The barge)
Do you want a game of tug of war? Well, it's up to you, you own it. (E) = Europe (your rope)
He's got American coins all down his spine. (N) = Nickelback
Jeremy Beadle has got a little bit of arthritis. What's going on there? (SLF) = Stiff Little Fingers
Foxy, Shipman and some country and western singer on a merry go round. (SD) = Spin Doctors (the country and western singer was Dr Hook.)
If you're going to France by boat, you might as well buy your fags there because you'll get 'em a lot cheaper. (BF) = Bryan Ferry (buy on ferry)
This little foreign cafe's growing its own steak. (DA) = Del Amitri (deli meat tree)
The Jamaican fella might have screamed this on the Titanic. (CD) = Chris DeBurgh (Christ, de berg!)
The doctor said part of the foot and the leg was no good, so he took 'em off and threw 'em away. (TB) = Tony Bennett (toe, knee, bin it!)
The Scottish monster has got a bit of a tan. (TD) = The Darkness (The dark ness)
Well, the 60's singer had a heart attack whilst he was 'avin it away. We won't be seeing him again. (FNM) = Faith No More (Adam Faith no more)
All the police cars are on fire. (BS) = Blazin' Squad
The director of "28 Days Later" is shouting about sleeping outside. (DB) = Daniel Bedingfield (Dan yell, "Bed in field!" (as in Danny Boyle))
He wants to be a sailor. Why's that? (B) = Beyoncé (be on sea)
This vegetable started life down under. (KO) = Kelly Osbourne (cauli Oz born)
The things that you normally find on the beach have been found floating round the moon. (TS) = The Specials (the space shells)
If you put that many in the post I'm surprised I didn't receive one. (FC) = 50 Cent (fifty sent)#
That Teletubby has got lice. (TP) = The Police
I'm saving that money to buy condoms. (JC) = Johnny Cash
When you're making bread, add a bit of color for a change. (D) = Dido (dye dough)
If you go to Chepstow you will. (S) = Seahorses (see horses)
ET's upset. What's he upset for, what's wrong with him? (ME) = Missy Elliot (missing Elliot)
I had a tape with Humpty Dumpty and Hickory Dickory Dock on it, but I broke it. (BR) = Busta Rhymes (busted rhymes)
I'm going to the north east. What are you going there for? (S) = Seal (see Hull)
Ah yeah, she's related to the man in the lamp, you know. (G) = Genesis (genie sis)
The Jamaican fella would love to live there, but it's a little bit pricey. (DS) = Dire Straits (dear streets)
I can't do any photos cos it's been nicked by a German. (AC) = Aztec Camera (has took/take camera)
If you keep eating, this part of your body will get bigger. (PC) = Phil Collins (fill colons)
The place where you go to take your dog a walk and that, or you might go there on a Sunday. People, sort of, might taste that area. (AP) = Alex Parks (A licks parks)
Will you leave the entrance to me garden alone? (GG) = Gareth Gates (ger'off gates)
Don't phone but you can send a message on me mobile. (T) = Texas (text us)
We were sharing out the male sheep and that, and I think I got the best one. (DG) = Delta Goodrem (dealt a good ram)
Don't be stealing my tools. Take your sister's. (NK) = Nik Kershaw (nick her saw)
Buy it if you want, I'm not that bothered. Think about it. Come back, right, come back if you want. Check some other places out first before you, you know. I'm not fussed. Shop around, come back. It's up to you. I'm not pushing you into anything. (SC) = Soft Cell
That's good, I can play ten pin bowling again. (O) = Outkast (as in I had a broken arm but now I'm out of my cast)
The Jamaican fella wrote a review for "Phoenix Nights." (DC) = Divine Comedy (da fine comedy)
We should all vote for Paul Daniels, David Blaine, Copperfield, The Great Soprendo, Tommy Cooper and Derren Brown. Why's that? What's going on there? (ES) = Electric Six (elect trick six)
Steve, what did your dad do? Ricky, what did your dad do? Can work on anyone. (E) = Erasure (he raised yer)
So if you got, like, a bulb and you look after it, and you teach it stuff and all that. What are you doing there? Do you know what I mean? (R) = Razorlight (raise a light)
People have a problem doing this when they get home from a night out drinking. What's the problem they've got? (K) = Keane (key in)
I had a vision of that Chinese flu. (C) = Caesars (see SARS)
The fella let his wife know how he got the bruise on his leg. (CL) = Courtney Love (caught knee, love)
That Potter lad has a lot of bottle messin' about with the wizards. (TB) = The Bravery (brave Harry)
The Buddhists won't be able to get into their temple without these. (TM) = The Monkees (monk keys)
There's a vehicle that sells kebabs. (D) = Donovan (donner van)
You're asked if you want that bit of the egg. You think about it, then you sort of decide against it. (YO) = Yoko Ono (yolk? oh... oh no)
I don't think this burger will catch on. (M) = McFly (as in a McDonalds burger made of flies)
Why don't you borrow some land off Mr. Boardman, Mr. Laurel or Mr. Fletcher? (LS) = Lisa Stansfield (lease a Stan's field)
I'm going to annoy those sea birds over there. (B) = Buggles (bug gulls)
What the Scouse fella said to the robber he found in his vineyard. (AW) = Amy Winehouse (ay, me wine house!)
When I'm ill I throw up horse food. What's going on there? (IH) = Isaac Hayes (I sick hays)
That garden tool isn't yours. Give it back. (ND) = Nick Drake (nicked rake)
That male sheep sounds fed up. Why's he fed up? (TR) = The Ramones (the ram moans)
Richard's kid cuts hair for a living. (BD) = Barbara Dickson (barber Dick's son)
I have a problem saying the French word for "well." (K) = Kasabian (can't say bien)
Take 52 kebabs, times that by 27 kebabs. The fella is struggling to work it out. (DS) = Donna Summer (donner sum, er?)
Put the, er...right, d'ya know them little information cards you get in a mobile phone? What's that called? But, put that on a spider's house. (SW) = Simon Webbe (SIM on web)
Diana Ross isn't, you know, sort of feeling that good at the moment. What's up with 'er? (ID) = Il Divo (ill diva)
That stuff that I put on my toast, *lick lick* it doesn't taste sharp enough. *lick lick* What's going on there? (JB) = James Blunt (jam's blunt)
I've got snails, croissants and baguettes in me palm. What's going on there? (FF) = Franz Ferdinand (French food in hand)
Me granny's taking a penalty. She better get the ball in the back of the net. (NM) = Nana Mouskouri (nanna must score 'ere)
I'm where people go to relieve themselves after looking at elephants and that. What am I? (A) = Amazulu (I'm a zoo loo)
I don't want a house that far away from the water. I want to be right on top of it. (B) = Beyonce (be on sea)
That part of me leg is English. (B) = Britney
The fitness teacher has got a speech impediment. (KW) = Kanye West (can we rest?)
Steal that women's flower. (RP) = Robert Plant (rob her plant)
Keep whacking the cooker with a stick. [It doesn't have to be a stick.] = (B) = Beethoven (beat oven)
Venice. It's all water, innit? How would you describe it? (M) = Morrissey (more is sea)
That Jamaican fella doesn't want anything. (ND) = Neil Diamond (nil demand)
I ask them to pass me the ball by using their head. (E) = Editors (head it [to] us)
He's got the woolly ones, but I've got the ones that run and charge at you. (R) = The Ramones (the ram ones)
I went to the restaurant on Monday, Tuesday, Wednesday, Thursday and Friday, Saturday and Sunday if you want, and the fella who makes the food was there each time. (SC) = Sam Cooke (same cook)
Go into that woman's store and rip her off. (C) = Cornershop (con her shop)
You've had a go at laying down a track, but it ain't perfect. (E) = Eurythmics (your rough mix)
Those songs you sing at Christmas, that bloke who sings 'em is brilliant at it. (CK) = Carole King
I ask you, Ricky, if you believe in Father Christmas. What do you say? (S) = Santana (Santa? nah)
That's a laptop... (A) = Adele (A dell)
The Spanish people are celebrating about the present they got for Jesus. (OM) = Olly Murs (Ole! Myrrhs!)
The Asian person's leg is a little bit angry. (TT) = Tinie Tempah (Thai knee temper)
This group would be good at doing your hair. (TP) = The Platters
This group sound like dinosaurs. (TR) = T. Rex
This group like to be by the sand and the sea. (TBB) = The Beach Boys
This guy sounds soup-perb. (GC) = Glen Campbell
This group are nice on toast. (TJ) = The Jam
This man liked his wine. (DM) = Dean Martin
Hope you're not speeding when you meet these. (TP) = The Police
Sounds like these lads work for the hospital.(GP) = Gerry and the Pacemakers
This group would go well with your Christmas dinner. (TC) = The Cranberries
They make a few good cupboards. (TC) = The Carpenters
This group thinks of lots of things. (I) = Imagination
She'd really like Blackpool. (FA) = Fairground Attraction
That army has got some well nice trenches. (DW) = Dandy Warhols (dandy war holes)
I really really love that woman. I love everything she does. (M) = Madonna (mad on her)
Well, I've had a rubbish day so I'm happy it's over. (GK) = Gladys Knight (glad it's night)
That woman's got her husbands gloves and a pair of her own. (HH) = Herman's Hermits (her man's, her mitts)
Do you think your kid will get that strawberry for me? (WP) = Wilson Picket (will son pick it?)
Me granny's taking a penalty. She better get the ball in the back of the net. (NM) = Nana Mouskouri (nanna must score 'ere)`;
